### ISSUE TITLE
Download link for latest versions seem broken

### ISSUE THREAD

**Issue by muffins** [osquery/osquery-site#100]
Looks like downloads are attempting to resolve `https://osquery.io/downloads/official/undefined/undefined/osquery-3.3.0.pkg`

**Comment by groob** [comment]
@muffins I suspect this is because the schema is missing the `platform` key. 
Compare 3.2.6, with 3.3

https://github.com/osquery/osquery-site/blob/20b764dfc02c9c336fef2b5b368fd30f224ab0ee/src/data/osquery_package_versions/3.2.6.json#L4-L11

and

https://github.com/osquery/osquery-site/blob/20b764dfc02c9c336fef2b5b368fd30f224ab0ee/src/data/osquery_package_versions/3.3.0.json#L4-L10

**Comment by muffins** [comment]
mmmmmmmmm, right you are!

**Comment by muffins** [comment]
This was addressed with #101
